const $=id=>document.getElementById(id),KEY="solar-predict-settings-v3";
const n=(id,d=0)=>{const el=$(id),v=el?+el.value:NaN;return Number.isFinite(v)?v:d};
function settings(){return{array1kwp:n("array1kwp",2),array1tilt:n("array1tilt",30),array1azimuth:n("array1azimuth",180),array2kwp:n("array2kwp",1),array2tilt:n("array2tilt",30),array2azimuth:n("array2azimuth",180),battery:n("battery",8),soc:n("soc",50),minSoc:n("minSoc",10),efficiency:n("efficiency",79),dayPrice:n("dayPrice",.31),nightPrice:n("nightPrice",.09),nightStart:n("nightStart",0),nightEnd:n("nightEnd",6),nightCharge:$("nightCharge").checked,lat:n("lat",53.4143),lon:n("lon",-3.0647)}}
function save(){localStorage.setItem(KEY,JSON.stringify(settings()))}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||"null");if(s)Object.keys(s).forEach(k=>{if($(k))$(k).type==="checkbox"?$(k).checked=!!s[k]:$(k).value=s[k]})}catch{}}
function estimate(r,kwp){const ghi=Math.max(0,r.shortwave_radiation||0),cloud=Math.max(0,Math.min(1,(r.cloud_cover||0)/100)),temp=r.temperature_2m??15;return Math.max(0,kwp*(ghi/1000)*.88*(1-.12*cloud)*(1-Math.max(0,temp-25)*.004))}
function batterySim(s,vals,times){const cap=Math.max(0,s.battery),min=cap*s.minSoc/100,eff=Math.sqrt(Math.max(.5,s.efficiency/100));let stored=Math.max(min,Math.min(cap,cap*s.soc/100)),solarToBattery=0,gridCharge=0;for(let i=0;i<vals.length;i++){const pv=vals[i],h=+times[i].slice(11,13);if(s.nightCharge&&cheap(h,s)&&cap>0&&stored<cap){const target=cap*.9;const input=Math.max(0,Math.min((target-stored)/eff,.5));stored+=input*eff;gridCharge+=input}if(pv>0&&cap>0&&stored<cap){const input=Math.min(pv,(cap-stored)/eff);stored+=input*eff;solarToBattery+=input}}return{solarToBattery,gridCharge,endSoc:cap?stored/cap*100:0,charged:solarToBattery+gridCharge}}
function cheap(h,s){return s.nightStart<s.nightEnd?h>=s.nightStart&&h<s.nightEnd:h>=s.nightStart||h<s.nightEnd}
async function forecast(){const s=settings();$("status").textContent="Fetching forecast…";const url="https://api.open-meteo.com/v1/forecast?latitude="+s.lat+"&longitude="+s.lon+"&hourly=shortwave_radiation,cloud_cover,temperature_2m&timezone=auto&forecast_days=2";try{const res=await fetch(url);if(!res.ok)throw Error("Weather service unavailable (HTTP "+res.status+")");const d=await res.json();if(!d.hourly||!d.hourly.time)throw Error("Forecast data was not returned");$("location").textContent=s.lat.toFixed(4)+", "+s.lon.toFixed(4)+" • "+d.timezone;const vals=d.hourly.time.map((_,i)=>{const r={shortwave_radiation:d.hourly.shortwave_radiation[i],cloud_cover:d.hourly.cloud_cover[i],temperature_2m:d.hourly.temperature_2m[i]};return estimate(r,s.array1kwp)+estimate(r,s.array2kwp)}),dates=d.hourly.time.map(x=>x.slice(0,10)),today=dates[0],tomorrow=dates.find(x=>x!==today),total=day=>vals.reduce((a,v,i)=>a+(dates[i]===day?v:0),0),a=total(today),b=total(tomorrow),sim=batterySim(s,vals,d.hourly.time);$("today").textContent=a.toFixed(2)+" kWh";$("todayKwh").textContent=a.toFixed(2)+" kWh";$("tomorrowKwh").textContent=b.toFixed(2)+" kWh";$("value").textContent="£"+(a*s.dayPrice).toFixed(2);$("batteryCharged").textContent=sim.charged.toFixed(2)+" kWh";$("solarToBattery").textContent=sim.solarToBattery.toFixed(2)+" kWh";$("endSoc").textContent=sim.endSoc.toFixed(0)+"%";const dayVals=vals.filter((_,i)=>dates[i]===today),max=Math.max(...dayVals,.01);let out="";d.hourly.time.forEach((t,i)=>{if(dates[i]!==today)return;const v=vals[i],h=t.slice(11,16);if(v<.005&&h<"05:00")return;out+="<div class='hour'><span>"+h+"</span><div class='bar'><i style='width:"+Math.min(100,v/max*100)+"%'></i></div><strong>"+v.toFixed(2)+" kWh</strong></div>"});$("hours").innerHTML=out||"<span class='muted'>No daylight generation expected.</span>";$("status").innerHTML="<span class='ok'>Updated successfully.</span>"}catch(e){$("status").innerHTML="<span class='error'>"+e.message+". Check your connection and try Update forecast again.</span>"}}
$("save").onclick=()=>{save();forecast()};$("gps").onclick=()=>{if(!navigator.geolocation)return alert("Location is not supported on this device.");navigator.geolocation.getCurrentPosition(p=>{$("lat").value=p.coords.latitude.toFixed(4);$("lon").value=p.coords.longitude.toFixed(4);save();forecast()},()=>alert("Location permission was not granted."))};load();forecast();
